import type { Metadata } from 'next';
import './globals.css';
import Footer from '@/components/navbar/Footer';
import Navbar from '@/components/navbar/Header';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Pawsmart.A',
  description: 'Generated by Pawsmart.A',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="min-h-screen">{children}</div>
        <Toaster richColors />
        <Footer />
      </body>
    </html>
  );
}
